### ISSUE TITLE
CPCS upload and Observatories

### ISSUE THREAD

**Issue by wyrzykow** [BHTOM-Team/bhtom2#100]
Po polsku bedzie.
W Manage Data.
Upload plikow. Photometry -> zmienic na Photometry file in SExtractor format
- mozna usunac (schowac na razie): Photometry limits

Pole: MJD obowiazkowe
- usunac pole ExpTime.
- observer: samo wypelnia sie default: User name, ale mozna to zmienic
- usunac Facility
- Observatory: z listy wlasnych obserwatoriow.
- Filter: default: GaiaSP/Any. Na liscie powinny byc tylko, jak na obrazku:
![image](https://github.com/BHTOM-Team/bhtom2/assets/26644157/c1957290-944f-4ea3-a647-58e73f18347a)
oraz 2MASS, jak na obrazku:
![image](https://github.com/BHTOM-Team/bhtom2/assets/26644157/29d5db7f-0532-482e-8ff9-ce4279ba04a0)

w Observatories, przy dodawaniu nowego (Create) - po zaznaczeniu pola Instrumental photometry only, nie trzeba podawac pozostalych pol, ani pliku przykladowego. Podobnie w Observatory/Details, tam tylko podstawowe info oraz info ze intrumental photometry only.

Reduced Datum: Facility: observatory name; Observer: observer name. 

Acha, w zasadzie mozliwe jest zeby user utworzyl dwa obserwatoria, ale jedno do instrumental_only, a drugie do fits/CCDPHOT. Musimy wymagac aby nazwa obserwatorium byla unikalna.

**Comment by wyrzykow** [comment]
Acha, i musimy pomyslec co zrobic z danymi ze starego CPCS. Wiekszosc z nich powinna zostac przeprocesowana (recalib) aby dopasowac do filtrow GaiaSP lub 2MASS. Zatem podczas przenoszenia targetow z BHTOM1 do BHTOM2 i danych z CPCS dla nich musi nastapic recalibracja.

**Comment by YuriiPurdenko** [comment]
Jest już poprawiony template upload 
Zostały do zrobienia "filters" i "observatory"
