### ISSUE TITLE
photometry vs instrumental photometry missing

### ISSUE THREAD

**Issue by wyrzykow** [BHTOM-Team/bhtom2#105]
In the evolution of the upload service, we lost one type of data: photometry. In TOM and BHTOM data_type=photometry is used in ReducedDatums, because it means a list of MJD,mag,magerr. 
However, in upload, when we say photometry, we mean SExtractor instrumental photometry upload, which is a different format: Ra,Dec,mag,magerr for a single MJD. In BHT1 we had both SExtractor instrumental as well as just photometry. We should sort this out, as this may cause errors. 
In Upload we need to add: "instrumental frame photometry in SExtractor format" which is the upload of .dat/.cat files, and "time-domain photometry file", which is going to be just creating ReducedDatums directly.

**Comment by YuriiPurdenko** [comment]
Done by @arturkrawczyk
