### ISSUE TITLE
importing Gaia Alerts does not read other parameters

### ISSUE THREAD

**Issue by wyrzykow** [BHTOM-Team/bhtom2#109]
Importing this:
name, GAIA_ALERTS_name, importance, cadence, description
Gaia14aaa,Gaia14aaa,0,100,old CPCS target imported
Gaia14aac,Gaia14aac,0,100,old CPCS target imported

ignored importance, cadence and description.

**Comment by wyrzykow** [comment]
still here. I uploaded this file:
name,GAIA_ALERTS_name,importance,cadence,description
Gaia24apw,Gaia24apw,7,1,microlensing candidate
Gaia24aqv,Gaia24aqv,7,1,microlensing candidate
Gaia24aqy,Gaia24aqy,7,1,microlensing candidate
Gaia24asr,Gaia24asr,10,0.1,binary microlensing candidate
Gaia24ata,Gaia24ata,10,0.5,long microlensing candidate
Gaia24atg,Gaia24atg,7,1,microlensing candidate

And all were created with importance = 9.99 and description unknown.

**Comment by YuriiPurdenko** [comment]
fixed
