### ISSUE TITLE
Set up Development Server for testing new functionalities and fixing errors

### ISSUE THREAD

**Issue by kkotysz** [BHTOM-Team/bhtom2#126]
**Objective:**
To establish a dedicated development server for testing new functionalities before deploying them to the production environment.

**Background:**
Currently, all development work is done directly on the production environment. This approach poses risks to the stability and integrity of our live application. By setting up a separate development server, we can ensure that new features and changes are thoroughly tested in an isolated environment before being rolled out to production.

**Priority:**
This issue should be prioritized to ensure timely setup of the development server and streamline our development process.

**Comment by tmac-rvx** [comment]
Due to the recent failure, the backup system needs to be improved. Work on launching the dev may slow down by a few days. I'm changing the milestone to EOW25.

**Comment by tmac-rvx** [comment]
Launched at https://test.bh-tom2.astrolabs.pl, currently in the final testing phase. After fixing the last bugs and completing the documentation, we will release it for use.

**Comment by wyrzykow** [comment]
@tmac-rvx could we have the documentation here? Or a pointer to the documentation? I would like to use the test server, but can not remember which repo goes where.
