### ISSUE TITLE
Accessing observatory fields with API

### ISSUE THREAD

**Issue by kkotysz** [BHTOM-Team/bhtom2#128]
The BH-TOM2 API lacks support for accessing recently added fields to observatory page: 

> Origin:
   Telescope name:
  Aperture [m]:
  Focal length [mm]:
  Seeing:

Please update the API to support access to newly added fields.

The same should be done also for updating an observatory via API.

**Comment by YuriiPurdenko** [comment]
Added fields to getObservatoryList and updateObservatory

**Comment by YuriiPurdenko** [comment]
Done
