### ISSUE TITLE
(!!!!) User cannot see if he/she attached a file during creating a new observatory

### ISSUE THREAD

**Issue by astromiki** [BHTOM-Team/bhtom2#133]
When user is creating an observatory, he/she cannot see whether the FITS file was attached properly

**Comment by YuriiPurdenko** [comment]
you mean in observatory details user can't download example fits to check if is it correct file?

**Comment by YuriiPurdenko** [comment]
![Screenshot from 2024-04-15 13-35-04](https://github.com/BHTOM-Team/bhtom2/assets/75389026/e29ef648-abbf-44c7-8f95-c50b0fd97319)
czy chodzi o te połę że jest słabo widoczne?

**Comment by astromiki** [comment]
please, make it so that everybody can see that the file has been attached
