### ISSUE TITLE
fits.fz, fits.gz & .zip files still not processed properly

### ISSUE THREAD

**Issue by astromiki** [BHTOM-Team/bhtom2#138]
FITS.FZ, FITS.GZ, ZIP files still not processed properly through ccdphotsvc. Although CCDPhot finishes calculations properly, some issue on the ccdphotsvc arrises when grabbing the *.dat file. See screenshots attached.
![image](https://github.com/BHTOM-Team/bhtom2/assets/19734606/21a5a08a-c64f-45b2-af49-8ab287d719cc)
![image](https://github.com/BHTOM-Team/bhtom2/assets/19734606/a7ace2d9-8efb-4fda-ba88-6bba672bc01e)

**Comment by astromiki** [comment]
http://ccdphot2.astrolabs.pl/jobs/157216/
It'not dat.

**Comment by majkelx** [comment]
| File | Filename  |
|--------|--------|
| Input file | `133_gaia23bab_n-v_300s_0001_F0ElYBe.fits.gz` |
| Expected output FITS file | `133_gaia23bab_n-v_300s_0001_F0ElYBe_s.fits.gz` |
| Actual output FITS file | `133_gaia23bab_n-v_300s_0001_F0ElYBe_s.fits ` | 

Output file has wrong extension (different form imput file)

**Comment by astromiki** [comment]
Ok, czyli to kwestia wyjściowych plików fits. Zatem no problem, poprawię , potestuję i wtedy zamykam issue.

**Comment by astromiki** [comment]
Dobra, skoro wyjściowy plik też ma mieć .gz, to tak też będzie. Chyba działa. Zamykam i dzięki!
