### ISSUE TITLE
Successfully processed files show error from ccdphotsvc

### ISSUE THREAD

**Issue by astromiki** [BHTOM-Team/bhtom2#139]
Sometimes files which have been processed succesfully through CCDPhot show error in REST API. This is a critical bug.
See screenshots attached.
![image](https://github.com/BHTOM-Team/bhtom2/assets/19734606/cabb774f-e52f-4755-940d-d22ca218a3c6)
![image](https://github.com/BHTOM-Team/bhtom2/assets/19734606/34033f94-e5a5-471b-b0c2-c001ab5fc076)

**Comment by majkelx** [comment]
Na pierwszy rzut oka nazwy plików z output nie odpowiadają źródłowemu

**Comment by majkelx** [comment]
| File | Filename  |
|--------|--------|
| Input file | `163_awa22015.fit_mod_0ZBYk9u.fit` |
| Expected output FITS file | `163_awa22015.fit_mod_0ZBYk9u_s.fit` |
| Actual output FITS file | `163_awa22015_mod_0ZBYk9u.fit_s.fit` | 
| Expected output DAT file | `163_awa22015.fit_mod_0ZBYk9u.dat` |
| Actual output DAT file | `163_awa22015_mod_0ZBYk9u.fit.dat` |

**Comment by astromiki** [comment]
Super, dzięki, spróbuję to jakoś ogarnąć i wtedy zamknę temat. Czy mogę dostać jakiś dostęp do takich logów, które Ty sprawdzasz?

**Comment by majkelx** [comment]
To sprawwdzam z Twojego raportu tylko i http://ccdphot2.astrolabs.pl/jobs/:

Input file - z `"fits_file": "http://ccdphot2.astrolabs.pl/files/fits/163_awa22015.fit_mod_0ZBYk9u.fit",`
Actual output files ze screenshot `=== RESULTS ===`
