### ISSUE TITLE
Add to Filters menu in Manage_Data (and upload) new options

### ISSUE THREAD

**Issue by wyrzykow** [BHTOM-Team/bhtom2#148]
In data upload (both GUI and API), currently people can choose Auto, 2MASS filters and GaiaSP/any or GaiaSP/filter. 

Add also the following options:
GaiaSP/ugriz - combining GaiaSP/u+g+r+i+z
GaiaSP/UBVRI - combining GaiaSP/U+B+V+R+I

Typically, people install these sets with their telescopes and that would be a better choice than GaiaSP/any.

Example: 
https://bh-tom2.astrolabs.pl/dataproducts/data/163753/
Should match to GaiaSP/R, but (after improvements of May 2024), matches best to GaiaSP/r, due to a low number of stars.

**Comment by YuriiPurdenko** [comment]
added to the database
