### ISSUE TITLE
Swagger not supported http in prod environments

### ISSUE THREAD

**Issue by arturkrawczyk** [BHTOM-Team/bhtom2#154]
The swagger not working in production environment. 

Cause: 

Failed to fetch.
Possible Reasons:

CORS
Network Failure
URL scheme must be "http" or "https" for CORS request.

**Comment by majkelx** [comment]
Is swagger expected to work on prod? Or it's temporary as long as dev env is not operational?

**Comment by tmac-rvx** [comment]
I suggest moving the swagger to dev

**Comment by majkelx** [comment]
Until @arturkrawczyk want it to be resolved on production faster?

**Comment by arturkrawczyk** [comment]
No, it has low priority
