### ISSUE TITLE
Store background, seeing and small cutouts per dataproduct

### ISSUE THREAD

**Issue by wyrzykow** [BHTOM-Team/bhtom2#155]
(this might be a duplicate with some other issues, sorry)

Each data product should store also background, seeing, airmass as well as small cutout from the centre of the image as png. It would allow immediately recognise problems with the image if failed or outlier.

Background, seeing and airmass should then also be stored within Reduced Datum, next to magnitude and error.
(and Reduced Datum should store the connection to its original dataproduct).

**Comment by astromiki** [comment]
Issue already exists. Closing.
