### ISSUE TITLE
BHTOM newsletter on web should show total stats

### ISSUE THREAD

**Issue by wyrzykow** [BHTOM-Team/bhtom2#189]
Total stats: 
- how many users total
- how many data points stored (together with archives) = reduced datums
- how many uploaded and processed (dataproducts), success rate
- how many targets total observed
- top score who uploaded most dataproducts

and then the same for last week.

**Comment by wyrzykow** [comment]
in last week stats we should have:
- number of new users registered
- number of new reduced datums
- number of new targets added
- number of new dataproducts uploaded
- top score for the last week uploaders.

**Comment by YuriiPurdenko** [comment]
ready to be tested
