### ISSUE TITLE
Target Name table API needed with all aliases

### ISSUE THREAD

**Issue by wyrzykow** [BHTOM-Team/bhtom2#201]
Ideally add this to the output of target list API.

**Comment by wyrzykow** [comment]
What is the test development server address?

**Comment by wyrzykow** [comment]
Does not work.  Aliases column is empty for all targets [], but the aliases should be, for example:
https://bh-tom2.astrolabs.pl/targets/Gaia22awa/

<img width="287" alt="image" src="https://github.com/user-attachments/assets/6db0d02e-e19a-4889-bd30-14dce5d07ff5">

All these should be listed.

**Comment by YuriiPurdenko** [comment]
fixed, ready to be tested
