### ISSUE TITLE
Problems with editing observatories in BHTOM administration

### ISSUE THREAD

**Issue by kkotysz** [BHTOM-Team/bhtom2#206]
When saving observatory with updated name this error appears:
![image](https://github.com/user-attachments/assets/07c29049-5a12-4d20-9ed2-4591c795bf58)
This error makes administration of observatories unusable.

**Comment by YuriiPurdenko** [comment]
allowed:  pattern = r'^[a-zA-Z0-9\-_+., :?\'"&apos;&#39;()@!~\r\n]*$'
