### ISSUE TITLE
CPCS matching radius fix

### ISSUE THREAD

**Issue by kkotysz** [BHTOM-Team/bhtom2#212]
Change fixed matching **radius == 2 arcsec** to more flexible parameter tied to sigma of astrometric solution. Examples of well reduced datums: one matched and one not matched below.

 - https://bh-tom2.astrolabs.pl/dataproducts/data/263446/ -> matched
 - https://bh-tom2.astrolabs.pl/dataproducts/data/263360/ -> not matched

**TOI** is conveniently marked in `.dat` file with **999999** object number.

**Comment by wyrzykow** [comment]
The idea is that we will use the actual matching radius based on the Ra-Dec cleaning we do at the very beginning of CPCS. We will then use sqrt(deltaRA^2+deltaDec^2) x 1.5 as the matching radius when identifying a target in the get_results method. Simple fix, but requires attention in coding.

**Comment by wyrzykow** [comment]
Coded, added to cpcs-test. Matching radius is found from Ra-Dec match and is used for target identification. **I use 2x sigma_ra_dec**, but we can then see if that is too large. 

Match_dist is stored in the db by the uploader, but then its value is updated after found by ra-dec. We store match_dist in arcseconds. Note the db contains a typo in the column name: match_distans, but it has to stay. 

Still need to test it for Gaia19eyy.

**Comment by wyrzykow** [comment]
Tested on Gaia19eyy. 
Computed the sigma of ra_dec to 2.6:
from cpcs log:
_-matching_dist used: 5.220130901027017
Target search: minimum distance found of 2.1321952094990215 arcsec_

![image](https://github.com/user-attachments/assets/7956f702-5cc4-48d7-a84b-7a7c1a23a4ff)

Works! Installed on cpcs-test. Can be moved to prod.
