### ISSUE TITLE
Target create form should require Description

### ISSUE THREAD

**Issue by wyrzykow** [BHTOM-Team/bhtom2#215]
In the Target Create form (after Catalog Search or after simple Target/Create), there is the field Description. It should be mandatory and it should require at least 10 characters. The description of the Description field should say: "Target description, mandatory, min 10 characters, for example: candidate supernova, or: old target, do not observe."

<img width="228" alt="image" src="https://github.com/user-attachments/assets/68924cc5-6d97-4d04-9f4d-d1e22aa524ee">

**Comment by wyrzykow** [comment]
we should also make this mandatory in the Import, but I don't know yet how to request this.

**Comment by YuriiPurdenko** [comment]
Done
