### ISSUE TITLE
Monitoring dashboard

### ISSUE THREAD

**Issue by maja-jablonska** [BHTOM-Team/bhtom2#31]
- Obciążenie bazy danych itd.
- Np. Grafana

**Comment by majkelx** [comment]
@wyrzykow, @tmac-rvx  : If this is not important right now, I suggest moving it back to the backlog until at least September.

**Comment by majkelx** [comment]
It's planned: 
- Prometeus
- Grafana
in the future

**Comment by arturkrawczyk** [comment]
move task to #172
