### ISSUE TITLE
Allow access to a target via its name in the bhtom address

### ISSUE THREAD

**Issue by wyrzykow** [BHTOM-Team/bhtom2#51]
instead of this:
http://visata.astrouw.edu.pl:8000/targets/9/
allow for this:
http://visata.astrouw.edu.pl:8000/targets/Gaia20azc

**Comment by arturkrawczyk** [comment]
dodałem w nowym branchu bhtom2-dev

**Comment by wyrzykow** [comment]
sorry, not "instead" but "as well" - we want to keep both possibilities to access the targets.

**Comment by PatrikSi** [comment]
All done

**Comment by wyrzykow** [comment]
tested, seems working, e.g. http://visata.astrouw.edu.pl:8000/targets/Gaia21dvx/
