### ISSUE TITLE
admin for Target does not display Aliases/names

### ISSUE THREAD

**Issue by wyrzykow** [BHTOM-Team/bhtom2#73]
Only the main name is displayed in bhtom admin:
<img width="818" alt="image" src="https://github.com/BHTOM-Team/bhtom2/assets/26644157/d62c3266-32ef-424d-8b9a-37e0fa5c6426">
but the target does have other names/aliases:
<img width="313" alt="image" src="https://github.com/BHTOM-Team/bhtom2/assets/26644157/f3851030-6838-4d37-9745-7a25df873bf4">

**Comment by arturkrawczyk** [comment]
![target](https://github.com/BHTOM-Team/bhtom2/assets/13250953/ac477846-7897-4fb1-b404-25c6952f3e83)
