### ISSUE TITLE
upload fits data flow

### ISSUE THREAD

**Issue by wyrzykow** [BHTOM-Team/bhtom2#79]
_Listing all ideas we had at a meeting in AKOND 26.Jun 2023, we should split this into smaller issues:_

Uploader in BHTOM becomes a separate microservice - to speed things up.

Uploader passes the fits file to ccdphotsvc for processing, feeding back to BHTOM with current status.
Once done, the instrumental photometry file (let's call it .cat) goes to CPCS (another microservice), where it gets stored and calibrated. The resulting mjd, mag, err returns to BHTOM and is stored as new Reduced Datum.

The new Reduced Datum stores the info on its origin, so the user name, the observatory/instrument/setup used, and filter it was calibrated to in CPCS. It also stores the **id** of the observation. 

The fits file upload fact is noted in Manage Data under My uploads(?) tab. The unique **id** is displayed and allows to DELETE that entry. Btw. we should also allow for bulk delete of points in some scripted way, similar to upload.

**Comment by YuriiPurdenko** [comment]
Done
