### ISSUE TITLE
Delete data

### ISSUE THREAD

**Issue by arturkrawczyk** [BHTOM-Team/bhtom2#86]
Add button to a website or chart to delete uploaded data

**Comment by wyrzykow** [comment]
Great. But what we need also is a possibility to delete: 
1. datasets added by brokers (linked to name aliases, but when I remove an alias, the data remains, for example, Target-Catalog Search-Gaia18ajz/Gaia Alerts, then in target Update remove Gaia Alerts alias, but the black data points remain).
2. individual datapoints coming from brokers - this could be a feature for admins only, that hovering over datapoint allows removing that specific ReducedDatum. How do we make sure it will not be downloaded again automatically after check for new data?

**Comment by wyrzykow** [comment]
so far removing data for admins (point 2) works in admin area, which is already useful.

**Comment by majkelx** [comment]
Pls, one task one issue. 

Initial ptoblem is solved
