### ISSUE TITLE
Classification

### ISSUE THREAD

**Issue by arturkrawczyk** [BHTOM-Team/bhtom2#97]
Prepare dictionary with Classification

**Comment by wyrzykow** [comment]
Unknown
Active Galactic Nucleus
BL Lac
Cataclysmic Variable
Cepheid Variable
Eclipsing Binary
Galaxy
Long Period Variable
Luminous Blue Variable
M-dwarf flare
Microlensing Event
Nova
Peculiar Supernova
Quasar
R CrB Variable
RR Lyrae Variable
Solar System Object
Star
Supernova
Supernova imposter
Symbiotic star
Tidal Disruption Event
Variable star-other
X-Ray Binary
Young Stellar Object

------
List copied and edited after Gaia Science Alerts. Will need to be modified sometimes with new classes. The default is Unknown

**Comment by YuriiPurdenko** [comment]
Status: Done and tested by myself
@wyrzykow please check it
