### ISSUE TITLE
what pages a regular user should see

### ISSUE THREAD

**Issue by wyrzykow** [BHTOM-Team/bhtom2#98]
I have created a regular user account. 
These are the menu items a regular user should only see:
- BHTOM (Home)
- Home - we have to rename it to About and make a new page
- Targets
- Target Grouping
- Data
- Observatory

Staff should also see: Alerts, Observations, Proposals and Users.

**Comment by YuriiPurdenko** [comment]
Hided and restricted access via url for regular users to Alerts, Observations, Proposals and Users

TODO: "Home - we have to rename it to About and make a new page"

**Comment by YuriiPurdenko** [comment]
Done
